<?php

namespace ApiBundle\Repository;

/**
 * announcementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class announcementRepository extends \Doctrine\ORM\EntityRepository
{
}
