<?php

namespace ApiBundle\Repository;

/**
 * medalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class medalRepository extends \Doctrine\ORM\EntityRepository
{
}
