<?php

namespace ApiBundle\Repository;

/**
 * tagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tagRepository extends \Doctrine\ORM\EntityRepository
{
}
