<?php

namespace ApiBundle\Repository;

/**
 * VerifiedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerifiedRepository extends \Doctrine\ORM\EntityRepository
{
}
